spring.application.name=alanya-backend
server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://localhost:3306/alanya_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=VALO LOVE 2040
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=alanyaSuperSecretKeyForJWTTokenGeneration2025ENSPY
jwt.expiration=900000
jwt.refreshExpiration=604800000
